version: 1.0.{build}
image: ubuntu
stack: node 8

build_script:
    - npm install
    - npm run lint
    - npm run build

artifacts:
    - path: build
      name: Halcyon.React
      type: Zip

deploy:
    - provider: Environment
      name: halcyon-react
